[package]
name = "moveline"
version = "0.1.0"
edition = "2021"
authors = ["Will Hopkins <willothyh@gmail.com>"]
description = "A neovim plugin to move lines up and down"
repository = "https://github.com/willothy/moveline.nvim"
license = "MIT"
readme = "README.md"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-utils = { git = "https://github.com/willothy/nvim-utils", branch = "dev" }
mlua = { version = "0.8.7", features = ["luajit", "vendored", "module"] }
